const jwt = require("jsonwebtoken");
const db = require("../database/db");

const JWT_SECRET =
  process.env.JWT_SECRET ||
  "accessguardai-development-secret";

function authenticateToken(req, res, next) {
  const authHeader = req.headers.authorization;

  /*
   * Expected:
   *
   * Authorization: Bearer <token>
   */

  if (!authHeader) {
    return res.status(401).json({
      success: false,
      message: "Authentication required.",
    });
  }

  const parts = authHeader.split(" ");

  if (
    parts.length !== 2 ||
    parts[0] !== "Bearer"
  ) {
    return res.status(401).json({
      success: false,
      message: "Invalid authorization format.",
    });
  }

  const token = parts[1];

  try {
    const decoded = jwt.verify(
      token,
      JWT_SECRET
    );

    /*
     * Support either userId or id in the JWT.
     *
     * This makes the middleware compatible
     * with the token generated by our auth routes.
     */

    const userId =
      decoded.userId || decoded.id;

    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Invalid authenticated user.",
      });
    }

    /*
     * Find the actual user in SQLite.
     */

    const user = db
      .prepare(`
        SELECT
          id,
          name,
          email
        FROM users
        WHERE id = ?
      `)
      .get(userId);

    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Invalid authenticated user.",
      });
    }

    /*
     * Store both the authenticated user
     * and decoded JWT on the request.
     */

    req.user = user;
    req.tokenPayload = decoded;

    next();

  } catch (error) {

    console.error(
      "Authentication error:",
      error.message
    );

    return res.status(401).json({
      success: false,
      message: "Invalid or expired token.",
    });
  }
}

module.exports = authenticateToken;